POST http://localhost:3001/api/blogs
Content-Type: application/json; charset=utf-8
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRoaXJkIiwiaWQiOjMsImlhdCI6MTY2MzIzNTk2MH0.nxAW1JSADeADs3o_ZhTHr3EYZwxtFRbNrgUproxRXOg


{
"author":"dhurmus", 
"url":"google.com",
"title": "fateko jutta"
}

### 
GET http://localhost:3001/api/blogs/

### 
GET http://localhost:3001/api/users/

### 
GET http://localhost:3001/api/authors/

###
DELETE http://localhost:3001/api/blogs/6

###
POST http://localhost:3001/api/users/
Content-Type: application/json; charset=utf-8


{
    "username":"forth",
    "name":"sita",
    "disabled": false
}

###
POST http://localhost:3001/api/login/
Content-Type: application/json; charset=utf-8

{
    "username":"third",
    "password":"secret"
}

### 
PUT http://localhost:3001/api/blogs/2
Content-Type: application/json; charset=utf-8

{
"likes": 3
}

###
PUT http://localhost:3001/api/users/username
Content-Type: application/json; charset=utf-8
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhhcmliYWhhZHVyIiwiaWQiOjEsImlhdCI6MTY2MjcxOTkzMX0.nzxHVkCHGKk6RFBWhaLpE4m1-1M0rglUpI4vnIFzNDE

{
    "disabled":false
}

###
POST http://localhost:3001/api/readinglists/
Content-Type: application/json; charset=utf-8


{
    "username":"forth",
    "name":"sita"
}